services:
  client:
    build:
      dockerfile: ./Dockerfile
      context: .
    env_file:
      - .env.dev
    ports:
      - 3000:3000
      - 6060:6060
  platform-client:
    build:
      dockerfile: ./Dockerfile
      context: .
    profiles: ["platform"]
